import "@/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Footer from "./components/Footer";
import NavBar from "./components/NavBar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex min-h-screen flex-col overflow-x-hidden bg-gray-950">
        <main className="m-4 flex flex-1 flex-col justify-center rounded-lg border border-slate-800 bg-slate-900">
          <NavBar />
          <div className="m-2 flex flex-1 text-white">{children}</div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
